services:
  redis-stack:
    restart: always
    image: whatwewant/redis-stack:${SERVICE_REDIS_STACK_IMAGE_VERSION}
    # ports:
    #   - 0.0.0.0:${SERVICE_REDIS_STACK_PORT}:6379
    #   - 0.0.0.0:${SERVICE_REDIS_STACK_PORT}:8001
    environment:
      # REDIS_ARGS: ${SERVICE_REDIS_STACK_REDIS_ARGS}
      REDISEARCH_ARGS: ${SERVICE_REDIS_STACK_REDISEARCH_ARGS:-"MAXSEARCHRESULTS 5"}
      # REDISJSON_ARGS: ${SERVICE_REDIS_STACK_REDISJSON_ARGS}
      # REDISGRAPH_ARGS: ${SERVICE_REDIS_STACK_REDISGRAPH_ARGS}
      # REDISTIMESERIES_ARGS: ${SERVICE_REDIS_STACK_REDISTIMESERIES_ARGS}
      # REDISBLOOM_ARGS: ${SERVICE_REDIS_STACK_REDISBLOOM_ARGS}

networks:
  default:
    external: true
    name: compose-ingress
